### PR TITLE
Post-Bullseye cleanup

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WAZO-3241
depends-on: https://github.com/wazo-platform/xivo-acceptance-server/pull/3

### CODE REVIEW

**Comment by DrPyser** [comment]
recheck

**Comment by DrPyser** [comment]
recheck

**Comment by DrPyser** [comment]
depends-on: https://github.com/wazo-platform/xivo-acceptance-server/pull/3

**Comment by DrPyser** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (the whole zuul list has been updated)

**Comment by fblackburn1** [comment]
recheck (wazo-c4 has been readded to the project list ... because we cannot wipe this project for now)

**Comment by fblackburn1** [comment]
recheck (wazo-c4 has been readded to the project list ... because we cannot wipe this project for now)

**Comment by fblackburn1** [comment]
recheck (fix typo in zuul config :zzz: )

**Comment by fblackburn1** [comment]
recheck (fastapi branch has been removed from wazo-sysconfd)

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
