### PR TITLE
IN-322 remove unused c4 playbooks/template

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
A new PR was created to address the referred nodeset jobs in wazo-docker repo.

See: https://github.com/wazo-platform/wazo-docker/pull/23

**Comment by jfbourque** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (new config was not applied)

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Review by jfbourque — APPROVED** [review]
Zuul is passing OK now. Aproving and merging

**Pull request merged**
